# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ISC Bind"
  org.opencontainers.image.description: "Bind DNS server"
  org.opencontainers.image.source: "https://github.com/cmsj/addon-bind"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
