name: Builder

env:
  BUILD_ARGS: "--test"
  MONITORED_FILES: "build.yaml config.yaml Dockerfile rootfs VERSION"
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: "addon-bind"
  ADDON_DIR: "bind"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed: ${{ steps.monitored_files.outputs.changed }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Check monitored files
        id: monitored_files
        run: |
          for file in ${{ env.MONITORED_FILES }}; do
              if [[ "${{ steps.changed_files.outputs.all }}" =~ ${{ env.ADDON_DIR }}/$file ]]; then
                echo "Detected a change in a monitored file: ${{ env.ADDON_DIR }}/$file"
                echo "changed=true" >> $GITHUB_OUTPUT
                exit 0
              fi
          done
          echo "Add-on had no monitored files changed (${{ env.MONITORED_FILES }})";

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

  build:
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    if: needs.init.outputs.changed == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ env.ADDON_DIR }}"

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.06.0
        with:
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          image-tags: |
            ${{ steps.info.outputs.version }}
            latest
          push: "true"
          version: ${{ steps.info.outputs.version }}

  manifest:
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Write needed for Cosign signing (issue OIDC token for signing)
      packages: write # To push the manifest to GitHub Container Registry
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          image-tags: |
            ${{ needs.build.outputs.info.version }}
            latest

      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: '${{ matrix.arch }}-addon-${{ env.ADDON_DIR }}'
          package-type: 'container'
          min-versions-to-keep: 5

